// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/User.proto

package com.fortis.test.user;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fortis.test.user.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string city = 1;</code>
   */
  java.lang.String getCity();
  /**
   * <code>string city = 1;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string region = 2;</code>
   */
  java.lang.String getRegion();
  /**
   * <code>string region = 2;</code>
   */
  com.google.protobuf.ByteString
      getRegionBytes();
}
