// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/User.proto

package com.fortis.test.user;

/**
 * Protobuf type {@code com.fortis.test.user.People}
 */
public  final class People extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.fortis.test.user.People)
    PeopleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use People.newBuilder() to construct.
  private People(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private People() {
    id_ = 0;
    name_ = "";
    children_ = java.util.Collections.emptyList();
    address_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private People(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              children_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            children_.add(input.readInt32());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              children_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              children_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              address_ = new java.util.ArrayList<com.fortis.test.user.Address>();
              mutable_bitField0_ |= 0x00000008;
            }
            address_.add(
                input.readMessage(com.fortis.test.user.Address.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        children_ = java.util.Collections.unmodifiableList(children_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        address_ = java.util.Collections.unmodifiableList(address_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fortis.test.user.User.internal_static_com_fortis_test_user_People_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fortis.test.user.User.internal_static_com_fortis_test_user_People_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fortis.test.user.People.class, com.fortis.test.user.People.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHILDREN_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Integer> children_;
  /**
   * <code>repeated int32 children = 3 [packed = true];</code>
   */
  public java.util.List<java.lang.Integer>
      getChildrenList() {
    return children_;
  }
  /**
   * <code>repeated int32 children = 3 [packed = true];</code>
   */
  public int getChildrenCount() {
    return children_.size();
  }
  /**
   * <code>repeated int32 children = 3 [packed = true];</code>
   */
  public int getChildren(int index) {
    return children_.get(index);
  }
  private int childrenMemoizedSerializedSize = -1;

  public static final int ADDRESS_FIELD_NUMBER = 4;
  private java.util.List<com.fortis.test.user.Address> address_;
  /**
   * <code>repeated .com.fortis.test.user.Address address = 4;</code>
   */
  public java.util.List<com.fortis.test.user.Address> getAddressList() {
    return address_;
  }
  /**
   * <code>repeated .com.fortis.test.user.Address address = 4;</code>
   */
  public java.util.List<? extends com.fortis.test.user.AddressOrBuilder> 
      getAddressOrBuilderList() {
    return address_;
  }
  /**
   * <code>repeated .com.fortis.test.user.Address address = 4;</code>
   */
  public int getAddressCount() {
    return address_.size();
  }
  /**
   * <code>repeated .com.fortis.test.user.Address address = 4;</code>
   */
  public com.fortis.test.user.Address getAddress(int index) {
    return address_.get(index);
  }
  /**
   * <code>repeated .com.fortis.test.user.Address address = 4;</code>
   */
  public com.fortis.test.user.AddressOrBuilder getAddressOrBuilder(
      int index) {
    return address_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (getChildrenList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(childrenMemoizedSerializedSize);
    }
    for (int i = 0; i < children_.size(); i++) {
      output.writeInt32NoTag(children_.get(i));
    }
    for (int i = 0; i < address_.size(); i++) {
      output.writeMessage(4, address_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < children_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(children_.get(i));
      }
      size += dataSize;
      if (!getChildrenList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      childrenMemoizedSerializedSize = dataSize;
    }
    for (int i = 0; i < address_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, address_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fortis.test.user.People)) {
      return super.equals(obj);
    }
    com.fortis.test.user.People other = (com.fortis.test.user.People) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && getChildrenList()
        .equals(other.getChildrenList());
    result = result && getAddressList()
        .equals(other.getAddressList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getChildrenCount() > 0) {
      hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
      hash = (53 * hash) + getChildrenList().hashCode();
    }
    if (getAddressCount() > 0) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddressList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fortis.test.user.People parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fortis.test.user.People parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fortis.test.user.People parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fortis.test.user.People parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fortis.test.user.People parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fortis.test.user.People parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fortis.test.user.People parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fortis.test.user.People parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fortis.test.user.People parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fortis.test.user.People parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fortis.test.user.People parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fortis.test.user.People parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fortis.test.user.People prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.fortis.test.user.People}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.fortis.test.user.People)
      com.fortis.test.user.PeopleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fortis.test.user.User.internal_static_com_fortis_test_user_People_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fortis.test.user.User.internal_static_com_fortis_test_user_People_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fortis.test.user.People.class, com.fortis.test.user.People.Builder.class);
    }

    // Construct using com.fortis.test.user.People.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAddressFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      name_ = "";

      children_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      if (addressBuilder_ == null) {
        address_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        addressBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fortis.test.user.User.internal_static_com_fortis_test_user_People_descriptor;
    }

    @java.lang.Override
    public com.fortis.test.user.People getDefaultInstanceForType() {
      return com.fortis.test.user.People.getDefaultInstance();
    }

    @java.lang.Override
    public com.fortis.test.user.People build() {
      com.fortis.test.user.People result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.fortis.test.user.People buildPartial() {
      com.fortis.test.user.People result = new com.fortis.test.user.People(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.name_ = name_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        children_ = java.util.Collections.unmodifiableList(children_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.children_ = children_;
      if (addressBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          address_ = java.util.Collections.unmodifiableList(address_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.address_ = address_;
      } else {
        result.address_ = addressBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fortis.test.user.People) {
        return mergeFrom((com.fortis.test.user.People)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fortis.test.user.People other) {
      if (other == com.fortis.test.user.People.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.children_.isEmpty()) {
        if (children_.isEmpty()) {
          children_ = other.children_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureChildrenIsMutable();
          children_.addAll(other.children_);
        }
        onChanged();
      }
      if (addressBuilder_ == null) {
        if (!other.address_.isEmpty()) {
          if (address_.isEmpty()) {
            address_ = other.address_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAddressIsMutable();
            address_.addAll(other.address_);
          }
          onChanged();
        }
      } else {
        if (!other.address_.isEmpty()) {
          if (addressBuilder_.isEmpty()) {
            addressBuilder_.dispose();
            addressBuilder_ = null;
            address_ = other.address_;
            bitField0_ = (bitField0_ & ~0x00000008);
            addressBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAddressFieldBuilder() : null;
          } else {
            addressBuilder_.addAllMessages(other.address_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fortis.test.user.People parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fortis.test.user.People) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> children_ = java.util.Collections.emptyList();
    private void ensureChildrenIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        children_ = new java.util.ArrayList<java.lang.Integer>(children_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated int32 children = 3 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getChildrenList() {
      return java.util.Collections.unmodifiableList(children_);
    }
    /**
     * <code>repeated int32 children = 3 [packed = true];</code>
     */
    public int getChildrenCount() {
      return children_.size();
    }
    /**
     * <code>repeated int32 children = 3 [packed = true];</code>
     */
    public int getChildren(int index) {
      return children_.get(index);
    }
    /**
     * <code>repeated int32 children = 3 [packed = true];</code>
     */
    public Builder setChildren(
        int index, int value) {
      ensureChildrenIsMutable();
      children_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 children = 3 [packed = true];</code>
     */
    public Builder addChildren(int value) {
      ensureChildrenIsMutable();
      children_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 children = 3 [packed = true];</code>
     */
    public Builder addAllChildren(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureChildrenIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, children_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 children = 3 [packed = true];</code>
     */
    public Builder clearChildren() {
      children_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private java.util.List<com.fortis.test.user.Address> address_ =
      java.util.Collections.emptyList();
    private void ensureAddressIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        address_ = new java.util.ArrayList<com.fortis.test.user.Address>(address_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.fortis.test.user.Address, com.fortis.test.user.Address.Builder, com.fortis.test.user.AddressOrBuilder> addressBuilder_;

    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public java.util.List<com.fortis.test.user.Address> getAddressList() {
      if (addressBuilder_ == null) {
        return java.util.Collections.unmodifiableList(address_);
      } else {
        return addressBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public int getAddressCount() {
      if (addressBuilder_ == null) {
        return address_.size();
      } else {
        return addressBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public com.fortis.test.user.Address getAddress(int index) {
      if (addressBuilder_ == null) {
        return address_.get(index);
      } else {
        return addressBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public Builder setAddress(
        int index, com.fortis.test.user.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressIsMutable();
        address_.set(index, value);
        onChanged();
      } else {
        addressBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public Builder setAddress(
        int index, com.fortis.test.user.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        address_.set(index, builderForValue.build());
        onChanged();
      } else {
        addressBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public Builder addAddress(com.fortis.test.user.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressIsMutable();
        address_.add(value);
        onChanged();
      } else {
        addressBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public Builder addAddress(
        int index, com.fortis.test.user.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressIsMutable();
        address_.add(index, value);
        onChanged();
      } else {
        addressBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public Builder addAddress(
        com.fortis.test.user.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        address_.add(builderForValue.build());
        onChanged();
      } else {
        addressBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public Builder addAddress(
        int index, com.fortis.test.user.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        address_.add(index, builderForValue.build());
        onChanged();
      } else {
        addressBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public Builder addAllAddress(
        java.lang.Iterable<? extends com.fortis.test.user.Address> values) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, address_);
        onChanged();
      } else {
        addressBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        addressBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public Builder removeAddress(int index) {
      if (addressBuilder_ == null) {
        ensureAddressIsMutable();
        address_.remove(index);
        onChanged();
      } else {
        addressBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public com.fortis.test.user.Address.Builder getAddressBuilder(
        int index) {
      return getAddressFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public com.fortis.test.user.AddressOrBuilder getAddressOrBuilder(
        int index) {
      if (addressBuilder_ == null) {
        return address_.get(index);  } else {
        return addressBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public java.util.List<? extends com.fortis.test.user.AddressOrBuilder> 
         getAddressOrBuilderList() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(address_);
      }
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public com.fortis.test.user.Address.Builder addAddressBuilder() {
      return getAddressFieldBuilder().addBuilder(
          com.fortis.test.user.Address.getDefaultInstance());
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public com.fortis.test.user.Address.Builder addAddressBuilder(
        int index) {
      return getAddressFieldBuilder().addBuilder(
          index, com.fortis.test.user.Address.getDefaultInstance());
    }
    /**
     * <code>repeated .com.fortis.test.user.Address address = 4;</code>
     */
    public java.util.List<com.fortis.test.user.Address.Builder> 
         getAddressBuilderList() {
      return getAddressFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.fortis.test.user.Address, com.fortis.test.user.Address.Builder, com.fortis.test.user.AddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.fortis.test.user.Address, com.fortis.test.user.Address.Builder, com.fortis.test.user.AddressOrBuilder>(
                address_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.fortis.test.user.People)
  }

  // @@protoc_insertion_point(class_scope:com.fortis.test.user.People)
  private static final com.fortis.test.user.People DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fortis.test.user.People();
  }

  public static com.fortis.test.user.People getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<People>
      PARSER = new com.google.protobuf.AbstractParser<People>() {
    @java.lang.Override
    public People parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new People(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<People> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<People> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.fortis.test.user.People getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

