// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/User.proto

package com.fortis.test.user;

public interface PeopleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fortis.test.user.People)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated int32 children = 3 [packed = true];</code>
   */
  java.util.List<java.lang.Integer> getChildrenList();
  /**
   * <code>repeated int32 children = 3 [packed = true];</code>
   */
  int getChildrenCount();
  /**
   * <code>repeated int32 children = 3 [packed = true];</code>
   */
  int getChildren(int index);

  /**
   * <code>repeated .com.fortis.test.user.Address address = 4;</code>
   */
  java.util.List<com.fortis.test.user.Address> 
      getAddressList();
  /**
   * <code>repeated .com.fortis.test.user.Address address = 4;</code>
   */
  com.fortis.test.user.Address getAddress(int index);
  /**
   * <code>repeated .com.fortis.test.user.Address address = 4;</code>
   */
  int getAddressCount();
  /**
   * <code>repeated .com.fortis.test.user.Address address = 4;</code>
   */
  java.util.List<? extends com.fortis.test.user.AddressOrBuilder> 
      getAddressOrBuilderList();
  /**
   * <code>repeated .com.fortis.test.user.Address address = 4;</code>
   */
  com.fortis.test.user.AddressOrBuilder getAddressOrBuilder(
      int index);
}
