// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/User.proto

package com.fortis.test.user;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fortis_test_user_People_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fortis_test_user_People_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fortis_test_user_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fortis_test_user_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020proto/User.proto\022\024com.fortis.test.user" +
      "\"h\n\006People\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\024\n\010" +
      "children\030\003 \003(\005B\002\020\001\022.\n\007address\030\004 \003(\0132\035.co" +
      "m.fortis.test.user.Address\"\'\n\007Address\022\014\n" +
      "\004city\030\001 \001(\t\022\016\n\006region\030\002 \001(\tB \n\024com.forti" +
      "s.test.userB\004UserH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_fortis_test_user_People_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fortis_test_user_People_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fortis_test_user_People_descriptor,
        new java.lang.String[] { "Id", "Name", "Children", "Address", });
    internal_static_com_fortis_test_user_Address_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_fortis_test_user_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fortis_test_user_Address_descriptor,
        new java.lang.String[] { "City", "Region", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
